steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t southamerica-west1-docker.pkg.dev/tienda-microservices-429001/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DB_POSTGRES_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'southamerica-west1-docker.pkg.dev/tienda-microservices-429001/image-registry/orders-ms',
    ]

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/184206400683/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'